server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${myblog.datasource.driver-class-name}
      url: jdbc:mysql://${myblog.datasource.host}:${myblog.datasource.port}/${myblog.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${myblog.datasource.username}
      password: ${myblog.datasource.password}
  mail:
    username: ${myblog.mail.username}
    password: ${myblog.mail.password}
    host: ${myblog.mail.host}
  redis:
      host: ${myblog.redis.host}
      port: ${myblog.redis.port}
      database: ${myblog.redis.database}

#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: deepseek-r1
#        options:
#          temperature: 0.7
#          top-p: 0.9
#          top-k: 40
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mybatis.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

myblog:
  jwt:
    # 设置jwt签名加密时使用的密匙
    user-secret-key: user
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的 令牌名称
    user-token-name: authentication
